### ISSUE TITLE
Unformatted LaTeX in Least Squares page

### ISSUE THREAD

**Issue by pwintz** [mcrovella/CS132-Geometric-Algorithms#15]
One of the equations is not formatted as an equation on this page: https://www.cs.bu.edu/fac/crovella/cs132-book/L22LeastSquares.html
![image](https://github.com/mcrovella/CS132-Geometric-Algorithms/assets/19618780/454c2df5-baf4-4acb-93bc-9636e39c3d1d)

**Comment by mcrovella** [comment]
Thanks - fixed.

**Comment by pwintz** [comment]
It looks like the problem is still live on the website. Do you expect it to be updated?

**Comment by mcrovella** [comment]
Looks OK to me - maybe your browser is caching the page?

**Comment by pwintz** [comment]
To check if it was a caching problem, I opened the BU site on a new device and the old version is still shown.

It appears that the problem is that the version on the BU website [here](http://mcrovella.github.io/CS132-Geometric-Algorithms/L22LeastSquares.html#when-an-inconsistent-system-is-better-than-a-consistent-system) is out of date whereas the version on Github [here](http://mcrovella.github.io/CS132-Geometric-Algorithms/L22LeastSquares.html#when-an-inconsistent-system-is-better-than-a-consistent-system) has the updates.

**Comment by mcrovella** [comment]
Thanks.  The BU website is obsolete – I’ll remove it.

From: Paul Wintz ***@***.***>
Date: Friday, February 23, 2024 at 3:32 PM
To: mcrovella/CS132-Geometric-Algorithms ***@***.***>
Cc: Mark Crovella ***@***.***>, State change ***@***.***>
Subject: Re: [mcrovella/CS132-Geometric-Algorithms] Unformatted LaTeX in Least Squares page (Issue #15)

To check if it was a caching problem, I opened the BU site on a new device and the old version is still shown.

It appears that the problem is that the version on the BU website here<http://mcrovella.github.io/CS132-Geometric-Algorithms/L22LeastSquares.html#when-an-inconsistent-system-is-better-than-a-consistent-system> is out of date whereas the version on Github here<http://mcrovella.github.io/CS132-Geometric-Algorithms/L22LeastSquares.html#when-an-inconsistent-system-is-better-than-a-consistent-system> has the updates.

**Comment by pwintz** [comment]
Oh, please don't delete the BU site completely! I have some links from my course website pointing to it. Would it be possible to add redirections to the other site instead?

**Comment by mcrovella** [comment]
Hi Paul, I'm glad you're finding the materials useful (and I appreciate the edits).   However the old pages are not updated any more (for at least 3 years now) and there's a lot that's been improved or corrected since then.   So I did remove the old site.   However you just need to change references to https://www.cs.bu.edu/fac/crovella/cs132-book/ to https://mcrovella.github.io/CS132-Geometric-Algorithms/ in your links.
